### ISSUE TITLE
Arduino uno with apds-9960 

### ISSUE THREAD

**Issue by lollo03** [sparkfun/APDS-9960_RGB_and_Gesture_Sensor#14]
I connect vcc to 3.3V, SDA to A4, SCL to A5. BUt when i try to run proximitysensor.ino in my serial monitor i have only this:

 SparkFun APDS-9960 - ProximitySensor

and nothing else... how i can fix it ??

**Comment by loricrotser** [comment]
Hello! Apologies for the delay in response - I have just been assigned this. :D 

I snagged an old Uno from our tech support guys and I was able to hook this up and get the ProximitySensor sketch running with no problem. Since the github issues are used for bugs and pull requests related to the libraries or pcbs, you may want to try the [forums](https://forum.sparkfun.com/index.php) to get more technical information, if you still need it. Thank you!
